book_call: Book a Call
book_call_link: https://meetings-eu1.hubspot.com/alessio-civitillo/the-scalable-way
newsletter:
  title: 'Subscribe to our Newsletter'
  consent_message: 'I would like to receive the newsletter. I can revoke this consent at any time by using the unsubscribe link provided in all communications. For more information, please review our [Privacy Policy](/privacy).'
  success_message: '✅ Thank you for subscribing! Your email has been successfully submitted.'
  error_message: '❌ Oops! Something went wrong. Please try again later.'
  consent_required: 'You must agree to the Privacy Policy before subscribing.'
