# Sveltia CMS configuration

# This is where we configure the CMS repo and its collections and fields
# Sveltia CMS generally follows the Decap CMS configuration spec
# Decap CMS docs: https://decapcms.org/docs/intro/
# Sveltia CMS docs: https://github.com/sveltia/sveltia-cms#features

local_backend: true

# Enter your GitHub repo path and branch (defaults to master)
backend:
  name: github
  repo: dyvenia/site-thescalableway
  branch: content

# The folder used to store uploaded images
media_folder: "/src/assets/images/"
public_folder: "/assets/images/"